In [1]:
# Importing numpy
import numpy as np

In [2]:
# creating a list
simple_list = [1,2,3]

# Converting it to numpy array
np.array(simple_list)

array([1, 2, 3])

In [3]:
# creating a list of list
list_of_list = [[1,2,3],[4,5,6],[7,8,9]]

# Converting it to numpy array
np.array(list_of_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
# arange function createa range of value from start and upper limit. Ending value is not inclusive
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# arrange can also have step value
np.arange(0,51,10)

array([ 0, 10, 20, 30, 40, 50])

In [7]:
# create array of zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
# create matrix of zeros
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
# create array of ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [10]:
# create matrix of ones
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
# create equaly spaced numbers from a given range
np.linspace(0,101,10)

array([  0.        ,  11.22222222,  22.44444444,  33.66666667,
        44.88888889,  56.11111111,  67.33333333,  78.55555556,
        89.77777778, 101.        ])

In [13]:
# Creating an identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
# creating a random value uniform distributed fro 0 to 1. 0 is inclusive while 1 is exclusibe
np.random.rand(3,3)

array([[0.25562897, 0.14753152, 0.43949968],
       [0.82981033, 0.42753993, 0.63958499],
       [0.36901382, 0.48613294, 0.76075955]])

In [16]:
# randn uses normally distributed set of values
np.random.randn(3,5)

array([[ 0.74400453,  0.62723752, -0.5038472 , -0.14051775, -1.39457273],
       [ 0.36225609, -0.10157421,  1.82831217,  0.305442  , -0.96775227],
       [-1.55736542,  0.0921666 ,  0.70356284, -1.38262566, -0.69781015]])

In [17]:
# creating a random integer between low and high value 20 is exclusive
np.random.randint(5,20)

7

In [18]:
# creating a random integer between low and high value 20 is exclusive
# and also mentioning no of values to be generated
np.random.randint(5,30,50)

array([24, 24, 19, 29, 12, 19,  5,  5,  9, 16, 29, 14, 28, 26, 27, 28,  9,
       17, 11, 18, 24, 29,  6, 23, 15, 11, 28, 29, 17, 11, 25, 22, 12, 28,
       17,  7, 20,  7, 29, 14, 10, 24, 28,  6, 20, 20, 26, 27, 20,  8])

In [19]:
# Creating a sample and random array and reshape the array

In [20]:
rand_array = np.random.randint(0,200,20)
rand_array

array([158,  67,   3,  65, 124, 115,  61,  38,  70,  72, 175,  18, 198,
       197,  97,  62,  54,  91,  27,  50])

In [21]:
sample_array = np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [22]:
sample_array.shape

(30,)

In [24]:
 sample_array.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [27]:
sample_array1 = sample_array.reshape(3,10)

In [28]:
sample_array1.shape

(3, 10)

In [29]:
sample_array.reshape(5,7)

ValueError: cannot reshape array of size 30 into shape (5,7)

In [30]:
rand_array

array([158,  67,   3,  65, 124, 115,  61,  38,  70,  72, 175,  18, 198,
       197,  97,  62,  54,  91,  27,  50])

In [31]:
# find max, min, index of max or min
rand_array.max()

198

In [32]:
rand_array.min()

3

In [33]:
rand_array.argmax()

12

In [34]:
rand_array.argmin()

2

In [35]:
# find the shape
rand_array.shape

(20,)

In [36]:
# find the datatype
rand_array.dtype

dtype('int32')

In [37]:
#to check function detals or help press Shift+Tab by hovering on function

In [38]:
rand_array.reshape(5,4)

array([[158,  67,   3,  65],
       [124, 115,  61,  38],
       [ 70,  72, 175,  18],
       [198, 197,  97,  62],
       [ 54,  91,  27,  50]])

In [39]:
# Transposing a matrix

In [40]:
rand_array.reshape(5,4).T

array([[158, 124,  70, 198,  54],
       [ 67, 115,  72, 197,  91],
       [  3,  61, 175,  97,  27],
       [ 65,  38,  18,  62,  50]])

In [41]:
# creating a sample array

In [42]:
sample_array = np.arange(10,21)

In [43]:
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [44]:
sample_array[8] #gets the 9th position/index

18

In [45]:
sample_array[2:5] #getting 3rd till 5th value

array([12, 13, 14])

In [46]:
sample_array[1:3]=100 #broadcasting a value at specific index of the array

In [47]:
sample_array

array([ 10, 100, 100,  13,  14,  15,  16,  17,  18,  19,  20])

In [48]:
# regenerating the same array
sample_array = np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [49]:
# Creating a subset of an array
subset_sample_array = sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [50]:
# broadcasting a value in subset array
subset_sample_array[:]=101
subset_sample_array

array([101, 101, 101, 101, 101, 101, 101])

In [51]:
sample_array

array([101, 101, 101, 101, 101, 101, 101,  17,  18,  19,  20])

In [52]:
# even the original array changed as subset is a view of original array or linked to original array

In [53]:
subset_sample_array = sample_array[0:7].copy()
subset_sample_array

array([101, 101, 101, 101, 101, 101, 101])

In [54]:
subset_sample_array[:]=99
subset_sample_array

array([99, 99, 99, 99, 99, 99, 99])

In [55]:
sample_array

array([101, 101, 101, 101, 101, 101, 101,  17,  18,  19,  20])

In [56]:
# when we use copy() it wont change the original array and sunset will become a copy

In [57]:
# Creating a matrix in numpy
sample_matrix = np.array(([1,2,3],[4,5,6],[7,8,9]))
sample_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
sample_matrix.dtype # checking the data type

dtype('int32')

In [59]:
sample_matrix.shape # checking the shape

(3, 3)

In [60]:
sample_matrix[0][2] # accessing the elements

3

In [61]:
sample_matrix[0,2] # accessing the elements

3

In [62]:
sample_matrix[2,:] # Slicing the matrix

array([7, 8, 9])

In [63]:
sample_matrix[2] # Slicing the matrix

array([7, 8, 9])

In [64]:
sample_matrix[:,(0,2)]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [65]:
sample_matrix[:,(2,0)]

array([[3, 1],
       [6, 4],
       [9, 7]])

In [66]:
sample_array = np.arange(1,31)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [67]:
bool = sample_array < 10 

In [68]:
bool

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False])

In [69]:
sample_array[bool] # get the array having values > 10 

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
sample_array[sample_array < 10] # get the array having values > 10 

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
sample_array + sample_array #Vector addition

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60])

In [72]:
sample_array - sample_array #Vector substraction

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [73]:
sample_array * sample_array #Vector Multiplication

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676,
       729, 784, 841, 900])

In [74]:
sample_array // sample_array #Vector division

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

In [75]:
sample_array + 10 #Vector addition 

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40])

In [76]:
# Using a built in functions

In [77]:
np.sqrt(sample_array) # Finding a square root

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
       5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558])

In [78]:
np.exp(sample_array) # Exponetial value e to the power of values

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
       7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
       3.93133430e+12, 1.06864746e+13])

In [79]:
np.log(sample_array) # Finding the log

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
       3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738])

In [80]:
np.max(sample_array)

30

In [81]:
np.min(sample_array)

1

In [82]:
np.argmax(sample_array)

29

In [83]:
np.argmin(sample_array)

0

In [84]:
np.sin(sample_array)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111,
       -0.99999021, -0.53657292,  0.42016704,  0.99060736,  0.65028784,
       -0.28790332, -0.96139749, -0.75098725,  0.14987721,  0.91294525,
        0.83665564, -0.00885131, -0.8462204 , -0.90557836, -0.13235175,
        0.76255845,  0.95637593,  0.27090579, -0.66363388, -0.98803162])

In [85]:
np.cos(sample_array)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153,
        0.0044257 ,  0.84385396,  0.90744678,  0.13673722, -0.75968791,
       -0.95765948, -0.27516334,  0.66031671,  0.98870462,  0.40808206,
       -0.54772926, -0.99996083, -0.53283302,  0.42417901,  0.99120281,
        0.64691932, -0.29213881, -0.96260587, -0.74805753,  0.15425145])

In [86]:
np.tan(sample_array)

array([ 1.55740772e+00, -2.18503986e+00, -1.42546543e-01,  1.15782128e+00,
       -3.38051501e+00, -2.91006191e-01,  8.71447983e-01, -6.79971146e+00,
       -4.52315659e-01,  6.48360827e-01, -2.25950846e+02, -6.35859929e-01,
        4.63021133e-01,  7.24460662e+00, -8.55993401e-01,  3.00632242e-01,
        3.49391565e+00, -1.13731371e+00,  1.51589471e-01,  2.23716094e+00,
       -1.52749853e+00,  8.85165604e-03,  1.58815308e+00, -2.13489670e+00,
       -1.33526407e-01,  1.17875355e+00, -3.27370380e+00, -2.81429605e-01,
        8.87142844e-01, -6.40533120e+00])

In [87]:
import numpy as np
array = np.random.randn(3,3)
array

array([[-2.42014087, -0.53355398, -0.48651139],
       [-0.30440916,  1.58181941, -0.41320907],
       [-0.58017463, -1.50751746,  0.34718511]])

In [88]:
np.round(array)

array([[-2., -1., -0.],
       [-0.,  2., -0.],
       [-1., -2.,  0.]])

In [89]:
np.round(array, decimals=2)

array([[-2.42, -0.53, -0.49],
       [-0.3 ,  1.58, -0.41],
       [-0.58, -1.51,  0.35]])

In [90]:
array

array([[-2.42014087, -0.53355398, -0.48651139],
       [-0.30440916,  1.58181941, -0.41320907],
       [-0.58017463, -1.50751746,  0.34718511]])

In [91]:
np.floor(array)

array([[-3., -1., -1.],
       [-1.,  1., -1.],
       [-1., -2.,  0.]])

In [92]:
np.ceil(array)

array([[-2., -0., -0.],
       [-0.,  2., -0.],
       [-0., -1.,  1.]])

In [93]:
np.std(array)

1.0436852660872702

In [94]:
np.mean(array)

-0.4796124492991802

In [95]:
np.median(array)

-0.48651138968169666

In [96]:
np.unique(array)

array([-2.42014087, -1.50751746, -0.58017463, -0.53355398, -0.48651139,
       -0.41320907, -0.30440916,  0.34718511,  1.58181941])

In [98]:
np.save('array',array) #Saving the array, saved in the working directory

In [99]:
np.savez('2_array.npz',a=array,b=sample_array) #Saving multiple array, saved in the working directory with savez

In [100]:
np.savetxt('array.txt',array,delimiter=',') # Saving the array in a text file

In [101]:
np.load('array.npy') # Loading an array from the saved file

array([[-2.42014087, -0.53355398, -0.48651139],
       [-0.30440916,  1.58181941, -0.41320907],
       [-0.58017463, -1.50751746,  0.34718511]])

In [102]:
archive = np.load('2_array.npz')

In [103]:
archive

In [104]:
archive['a']

array([[-2.42014087, -0.53355398, -0.48651139],
       [-0.30440916,  1.58181941, -0.41320907],
       [-0.58017463, -1.50751746,  0.34718511]])

In [105]:
archive['b']

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [106]:
np.loadtxt('array.txt', delimiter=',')

array([[-2.42014087, -0.53355398, -0.48651139],
       [-0.30440916,  1.58181941, -0.41320907],
       [-0.58017463, -1.50751746,  0.34718511]])